# Generated by Django 2.2.1 on 2019-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
